//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactDb
    {
        public int ID { get; set; }
        public string DomainURL { get; set; }
        public string contact { get; set; }
        public string contactName { get; set; }
        public string contactRole { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    }
}
